# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


# By --> Mahimai Raja J

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.21.6


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [7]:
print(vector.size)

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
vector = np.arange(10) == 4
vector = vector * 1
vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [43]:
import numpy as np
vector = np.arange(10,51)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [44]:
print(vector[::-1])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [47]:
matrix =  np.arange(0, 9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [48]:
vector = np.array([1,2,0,0,4,0])
non_zero = np.nonzero(vector)
print(non_zero)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [49]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [69]:
x = np.random.random((3,3,3))
print(x)

[[[0.68488086 0.79739422 0.63400476]
  [0.13160211 0.07550922 0.38810037]
  [0.9495573  0.97336579 0.28208013]]

 [[0.69752444 0.86243338 0.23999342]
  [0.23341491 0.46478318 0.86007435]
  [0.72896738 0.86659073 0.64093719]]

 [[0.01303922 0.50678577 0.12565678]
  [0.33290566 0.30795376 0.12469697]
  [0.68554179 0.69220024 0.46748435]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [71]:
x = np.random.random((10,10))
print(x) 
print(x.shape)
xmin, xmax = x.min(), x.max()
print(f"Minimum : {xmin}\nMaximum Values : {xmax}")

[[0.93926446 0.61535113 0.97463999 0.62236974 0.78258313 0.063446
  0.16957256 0.75864886 0.0397503  0.31851317]
 [0.34301914 0.47077956 0.48898725 0.06872863 0.15408361 0.28734101
  0.17420895 0.84984271 0.14043701 0.07505396]
 [0.22456465 0.15899586 0.73854746 0.19192726 0.50654129 0.46605249
  0.40229463 0.80706037 0.47877244 0.50140413]
 [0.66595232 0.18190543 0.66241796 0.46504522 0.26010014 0.32455604
  0.93105079 0.89362024 0.50127331 0.021178  ]
 [0.85456592 0.47881755 0.56707514 0.28669535 0.25917903 0.78455067
  0.52741734 0.96691071 0.9647554  0.55004987]
 [0.96989613 0.90880576 0.85647364 0.15973767 0.97569756 0.68625024
  0.57244237 0.40837906 0.04461471 0.58054178]
 [0.30303038 0.63460756 0.22935846 0.56833372 0.21765473 0.37893587
  0.42913362 0.56525249 0.16764186 0.76697673]
 [0.48139267 0.93923766 0.17150141 0.01093169 0.09610115 0.06612008
  0.99447485 0.76417953 0.52340006 0.35247235]
 [0.23722354 0.78679961 0.68532395 0.60389132 0.89160025 0.49299555
  0.91426978 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [73]:
x = np.random.random(10)
print(x)
mean = x.mean()
print(f'mean = {mean}')

[0.66151218 0.19640548 0.177492   0.04911723 0.36974599 0.87130956
 0.47791671 0.32950359 0.54316373 0.87929898]
mean = 0.45554654321029836


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [75]:
x = np.ones((6,6))
print(x,'\n')
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [76]:
x = np.ones((3,3))
print(x,'\n')
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [78]:
0 * np.nan

nan

In [79]:
np.nan == np.nan

False

In [80]:
np.inf > np.nan

False

In [81]:
np.nan - np.nan

nan

In [82]:
np.nan in set([np.nan])

True

In [83]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [85]:
a = np.zeros(25).reshape(5,5)

s = np.arange(len(a))
a[s[:-1], s[1:]] = [10,20,30,40]
a

array([[ 0., 10.,  0.,  0.,  0.],
       [ 0.,  0., 20.,  0.,  0.],
       [ 0.,  0.,  0., 30.,  0.],
       [ 0.,  0.,  0.,  0., 40.],
       [ 0.,  0.,  0.,  0.,  0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [90]:
x = np.ones((3,3),dtype=int)
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [103]:
vector =  np.arange(0,336).reshape(6,7,8)
posi = np.unravel_index(100, vector.shape)
posi


(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [116]:
num = np.arange(0,2)
repeat = 32
result = np.tile(num,repeat)
result.reshape(8,8)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [119]:
non_norm = np.random.random((3,3))
print(non_norm,'\n')
dfmax, dfmin = df.max(), df.min()
norm = (non_norm - dfmin)/(dfmax - dfmin)
print(df)

[[0.20976685 0.79921973 0.21785659]
 [0.07090938 0.81544092 0.11662145]
 [0.06532192 0.98153883 0.03412398]] 

[[0.02792831 0.30579627 1.        ]
 [0.         0.45850597 0.16050306]
 [0.39790892 0.99713271 0.87000543]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [122]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)
print(type(color))

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
<class 'numpy.dtype[void]'>


/Users/mahimairaja/opt/anaconda3/envs/flask/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [123]:
x = np.arange(15).reshape((5, 3))
y = np.arange(6).reshape((3, 2))
np.dot(x, y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [125]:
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1
x

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [134]:
print(sum(range(5), -1))

# It prints as 9

10


In [135]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [144]:
Z = np.arange(3)

In [137]:
2 << Z >> 2

array([0, 1, 2])

In [146]:
Z <- Z

array([False, False, False])

In [139]:
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j])

In [142]:
Z/1/1

array([0., 1., 2.])

In [147]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [148]:
np.array(0) / np.array(0)

/Users/mahimairaja/opt/anaconda3/envs/flask/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [149]:
np.array(0) // np.array(0)

/Users/mahimairaja/opt/anaconda3/envs/flask/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [150]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [151]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([ -8.,  10.,  -7.,   5., -10.,  -4.,   3.,  -7.,   5.,   6.])

#### 30. How to find common values between two arrays? (★☆☆)

In [152]:
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [153]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [154]:
Z

array([inf])

In [155]:
_ = np.seterr(**defaults)
Z = np.ones(1) / 0

/Users/mahimairaja/opt/anaconda3/envs/flask/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [156]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) 

False


/Users/mahimairaja/opt/anaconda3/envs/flask/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [165]:
today = np.datetime64('today', 'D')
print("Today: ", today)
  
# for yesterday
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
  
print("Yestraday: ", yesterday)
  
# for tomorrow
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
  
print("Tomorrow: ", tomorrow)

Today:  2022-08-10
Yestraday:  2022-08-09
Tomorrow:  2022-08-11


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [167]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
x

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [168]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [169]:
x = np.random.uniform(-10, +10, 10)
x.astype(np.int32)
np.trunc(x)

array([-7.,  5., -9., -4., -0.,  5.,  7.,  2., -2., -3.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [170]:
x = np.zeros((5, 5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [171]:
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [172]:
x = np.linspace(start=0, stop=11, num=10, endpoint=False)
x

array([0. , 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [174]:
x = np.random.random(size=10)
x.sort()
x

array([0.00655543, 0.06733076, 0.07975977, 0.16976031, 0.27306444,
       0.46541282, 0.53031168, 0.57037911, 0.65725737, 0.91926135])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [175]:
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

6.393194198608398


In [176]:
begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

4.456996917724609


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [177]:
A = np.arange(10)
B = np.arange(10)
np.array_equal(A, B)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [178]:
x = np.zeros(10)
x.flags.writeable = False
x[1] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [180]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R,'\n')
print(T)

[0.56326492 0.78831581 0.94635491 0.49319065 0.56831069 1.00345162
 0.36208097 0.59364735 0.71322246 0.39589483] 

[0.59417709 0.73522138 0.63606996 1.55024911 1.05289437 1.06654217
 1.471245   1.48937452 1.02204343 0.89457341]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [182]:
x = np.random.random(10)
x[x == np.max(x)] = 0
x[x.argmax()] = 0
x

array([0.60502856, 0.08079525, 0.57015971, 0.        , 0.        ,
       0.58880326, 0.27683702, 0.25533311, 0.77079595, 0.85304695])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [185]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(x,'\n\n',y)

[0.60502856 0.08079525 0.57015971 0.         0.         0.58880326
 0.27683702 0.25533311 0.77079595 0.85304695] 

 [ 5  6  7  8  9 10 11 12 13 14]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [189]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)
print(x,'\n\n',y)

[[2.93697578e-02 5.13964004e-01 9.27528767e-01 4.18497927e-01
  6.86771021e-01]
 [3.98084327e-01 8.80967724e-01 4.17354072e-01 2.53894724e-01
  3.05317836e-01]
 [2.87019086e-01 8.96526002e-01 1.13516255e-02 2.02566329e-01
  3.60608715e-01]
 [4.28122725e-01 3.57740881e-01 9.80484475e-01 9.56422819e-01
  7.61609140e-01]
 [4.52217226e-01 9.33556357e-01 1.81848831e-01 1.27745357e-01
  8.85006372e-04]] 

 [[0.41933929 0.80510661 0.42093829 0.0910478  0.05503449]
 [0.43210648 0.99776288 0.43867423 0.06471456 0.64830213]
 [0.15590989 0.30597844 0.52718893 0.52504157 0.79522451]
 [0.4327681  0.51012298 0.01335288 0.10965956 0.74918978]
 [0.89987102 0.01765617 0.42414454 0.02276107 0.48817785]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [192]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
print('\n')
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [197]:
np.set_printoptions(threshold=np.inf, linewidth=np.nan)
Z = np.zeros((160,160))
print(Z)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [202]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()

print(Z[index])

83


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [203]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]), ('color', [ ('r', float, 1),('g', float, 1),('b', float, 1)])])

print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/Users/mahimairaja/opt/anaconda3/envs/flask/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [205]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.5127997  0.55460962 0.43654187 0.49696378 0.34681336 0.50440806 0.20842625 0.35740428 0.59310628]
 [0.5127997  0.         0.3590418  0.38306816 0.19171265 0.41122492 0.73999643 0.32075791 0.45612692 0.29413121]
 [0.55460962 0.3590418  0.         0.68028199 0.53508095 0.66454844 0.48517244 0.36819931 0.70608693 0.10096807]
 [0.43654187 0.38306816 0.68028199 0.         0.20994959 0.09921881 0.88476796 0.39474599 0.12131161 0.6490306 ]
 [0.49696378 0.19171265 0.53508095 0.20994959 0.         0.26889381 0.84532333 0.36173318 0.30970992 0.48180712]
 [0.34681336 0.41122492 0.66454844 0.09921881 0.26889381 0.         0.81602131 0.34082232 0.0450382  0.64798091]
 [0.50440806 0.73999643 0.48517244 0.88476796 0.84532333 0.81602131 0.         0.49533914 0.83948011 0.58337699]
 [0.20842625 0.32075791 0.36819931 0.39474599 0.36173318 0.34082232 0.49533914 0.         0.37417106 0.39154915]
 [0.35740428 0.45612692 0.70608693 0.12131161 0.30970992 0.0450382  0.83948011 0.37417106 0.    

In [206]:
import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.39420225 0.87551631 0.61092153 0.267843   0.49577359 0.08440894 0.36169106 0.37580238 0.19587607]
 [0.39420225 0.         0.67091114 0.23103127 0.45274767 0.16408343 0.35176137 0.20761908 0.38609602 0.19913115]
 [0.87551631 0.67091114 0.         0.53976697 1.07008836 0.51129133 0.89579422 0.87744633 0.51694528 0.76619459]
 [0.61092153 0.23103127 0.53976697 0.         0.68117512 0.13531753 0.57850566 0.4121244  0.47337786 0.42242101]
 [0.267843   0.45274767 1.07008836 0.68117512 0.         0.60582083 0.19889421 0.29072778 0.61323527 0.30398696]
 [0.49577359 0.16408343 0.51129133 0.13531753 0.60582083 0.         0.47521065 0.37135912 0.3408001  0.31965461]
 [0.08440894 0.35176137 0.89579422 0.57850566 0.19889421 0.47521065 0.         0.28578608 0.41790574 0.15662645]
 [0.36169106 0.20761908 0.87744633 0.4121244  0.29072778 0.37135912 0.28578608 0.         0.52899759 0.20946114]
 [0.37580238 0.38609602 0.51694528 0.47337786 0.61323527 0.3408001  0.41790574 0.52899759 0.    

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [209]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [213]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
6, , , 7, 8\n
, , 9,10,11\n""")

Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)

print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [215]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [216]:
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [218]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0

G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)
print(G.shape)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818 0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022 0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308 0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367 0.69905581 0.63331324 0.5461

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [229]:
n = 10
randomNumber = 99  # <--- P elements
Z = np.zeros((n,n))

np.put(Z, np.random.choice(range(n*n), randomNumber, replace=False),1)
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [230]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[-0.29962013  0.03883869  0.27590881 -0.23687439  0.09202332 -0.16798571 -0.18438949 -0.11404767  0.32731703  0.26882953]
 [ 0.33635593  0.06319104  0.19310235  0.3057164  -0.25988581  0.20197831 -0.17854189 -0.54570833 -0.1522246   0.03601659]
 [-0.20219556  0.26014159 -0.4596816  -0.07402205  0.10043875  0.17238577 -0.25843953 -0.04757572  0.34009838  0.16884997]
 [ 0.2561544   0.28786544  0.11811519  0.17619971 -0.41633206  0.09479944 -0.50939774  0.05654087  0.10451791 -0.16846316]
 [-0.35942622  0.23194352 -0.43659409 -0.24050291  0.49686523  0.15087383 -0.44595836  0.40766803  0.16696571  0.02816528]]


#### 59. How to sort an array by the nth column? (★★☆)

In [234]:
Z = np.random.randint(0,10,(3,3))
print(Z,'\n')
print(Z[Z[:,1].argsort()])


[[2 2 1]
 [1 8 5]
 [4 9 7]] 

[[2 2 1]
 [1 8 5]
 [4 9 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [235]:
Z = np.random.randint(0,3,(3,10))

print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [237]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]

print(Z,'\n')
print(m)

[0.20338373 0.61701139 0.64933911 0.41236061 0.39456965 0.83515691 0.27537061 0.31576787 0.62378224 0.4015395 ] 

0.4123606103034073


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [241]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

it = np.nditer([A,B,None])

for x,y,z in it: 
    z[...] = x + y
    
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [243]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: 
            return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "Name_Attribute")
print (Z.name)

Name_Attribute


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [244]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))

print(Z)

[4. 2. 3. 4. 2. 2. 1. 1. 7. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [245]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [246]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))

print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [249]:
A = np.random.randint(0,10,(3,4,3,4))
print(A,'\n')
Sum = A.sum(axis=(-2,-1))

print(Sum)

[[[[6 3 0 9]
   [5 6 1 8]
   [6 2 7 8]]

  [[1 5 2 2]
   [0 0 7 0]
   [3 1 5 2]]

  [[1 6 5 1]
   [1 0 7 2]
   [7 6 9 8]]

  [[2 5 8 9]
   [1 4 3 8]
   [0 4 9 3]]]


 [[[9 7 7 4]
   [0 0 9 9]
   [4 2 4 4]]

  [[3 1 1 5]
   [9 5 2 0]
   [8 4 8 9]]

  [[0 7 3 5]
   [2 9 6 8]
   [5 6 7 3]]

  [[0 1 1 6]
   [7 7 0 6]
   [3 5 9 6]]]


 [[[2 7 5 4]
   [9 0 9 9]
   [3 1 2 8]]

  [[0 6 5 1]
   [9 3 1 7]
   [9 3 0 4]]

  [[5 3 0 7]
   [1 1 0 3]
   [7 3 5 0]]

  [[8 2 7 5]
   [2 8 5 3]
   [7 5 1 2]]]] 

[[61 28 53 56]
 [59 55 61 51]
 [59 48 35 55]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [250]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts

print(D_means)

[0.59876183 0.47196189 0.48717289 0.51301888 0.41982076 0.46172426 0.30876338 0.52646546 0.46323889 0.52982163]


#### 69. How to get the diagonal of a dot product? (★★★)

In [253]:
A = np.random.uniform(0,1,(5,5))

B = np.random.uniform(0,1,(5,5))

x = np.einsum("ij,ji->i", A, B)
print(A,'\n\n',B,'\n\n',x)

[[0.44324444 0.86479061 0.16408886 0.4223766  0.01696824]
 [0.83243215 0.22747581 0.29733929 0.85194517 0.66793667]
 [0.87925293 0.74866916 0.66296786 0.90884389 0.36062514]
 [0.27563695 0.01212732 0.57237709 0.12974483 0.13446905]
 [0.63724288 0.01813806 0.50135452 0.08704058 0.7980243 ]] 

 [[0.12996784 0.13447996 0.29541782 0.19198968 0.33347981]
 [0.09511194 0.63336604 0.2713103  0.74956687 0.10895962]
 [0.34176689 0.14799897 0.41130686 0.71584901 0.69485183]
 [0.98405505 0.43100329 0.66474809 0.6453655  0.85549488]
 [0.57926588 0.39184894 0.84229438 0.54923469 0.34987625]] 

 [0.62141053 0.92894825 1.64345663 0.62933316 0.91652357]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [255]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z

print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [256]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))

print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [257]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]

print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [258]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)

print(G)

[( 3, 16) ( 3, 54) ( 6, 48) ( 6, 58) ( 9, 58) ( 9, 61) (16, 54) (16, 66) (16, 83) (17, 22) (17, 24) (18, 46) (18, 83) (22, 24) (24, 24) (24, 85) (27, 28) (27, 86) (28, 86) (42, 50) (46, 83) (48, 58) (50, 50) (50, 74) (50, 76) (58, 61) (66, 83) (74, 76)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [259]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [260]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [261]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)

print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [264]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.99460353, -0.98319648, -0.47095076, -0.86086707,  0.89245367, -0.55852418,  0.6103697 ,  0.09982248,  0.20071583,  0.25780759, -0.98607702, -0.18361769, -0.08797474,  0.14555995,  0.85519543,  0.23666773, -0.77473478, -0.9136101 ,  0.37602248,  0.23299245,  0.23598719, -0.33794222, -0.59325689, -0.67089924,  0.04637909,  0.54704268, -0.74967631, -0.86211553,  0.49486975, -0.63153801, -0.56339557,  0.47044866,  0.38628168, -0.83296288,  0.26621856, -0.12317249, -0.77561029,  0.04478354,  0.15662051, -0.34085846, -0.45546669, -0.72841853, -0.52690486, -0.34709064,  0.5338327 , -0.007391  , -0.69528896, -0.19492877, -0.28011469,  0.90396479, -0.90215084, -0.41909492, -0.88347776,  0.659904  ,  0.94898743,  0.44800891,  0.58837277, -0.58750408,  0.80775712,  0.74175026, -0.30019901, -0.06523731, -0.41561417,  0.85672002,  0.4012302 , -0.40567421,  0.12727841, -0.73566475, -0.16931276, -0.25114659, -0.46377896, -0.84005694,  0.60250126,  0.37755996,  0.93177172,  0.97095244,  0.41

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [265]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))

p = np.random.uniform(-10,10,( 1,2))

print(distance(P0, P1, p))

[ 0.44804406 12.79715313  1.74035313  3.65213183  0.53938021  5.0967321   1.1684518   5.06377647  8.66946808  1.9244219 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [266]:
P0 = np.random.uniform(-10, 10, (10,2))

P1 = np.random.uniform(-10,10,(10,2))

p = np.random.uniform(-10, 10, (10,2))

print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.73732737 11.41104885  3.23651837  3.25936275  7.70890962  3.05038231  3.76776616  4.96701916  5.80420045  9.52509093]
 [11.49654628 12.38466172  2.83374245  5.99754474  1.68178249 11.2212965  11.19741297  4.84114611 14.29354398  8.79188074]
 [ 3.74860954  5.49900378  0.17190417  3.00377469  4.27287356  1.68932871  1.3978551   7.35590496  1.3000244   3.91821204]
 [10.15047239  0.28397008  7.52735633  2.88522748  3.08619026  1.84398094  2.46116376  3.98344602  1.59238503  2.57081499]
 [ 0.72778952  8.80911361  3.5601477   5.70412898  8.00977471  1.0679724   0.31489532  8.60747193  1.69127045  7.51302261]
 [ 1.39665097  6.25545841  1.91550594  5.35197961  6.35420868  2.92311761  2.37510321  9.39457007  0.05285077  5.04811466]
 [ 3.0717574   4.31916347  0.1992831   3.86817966  4.23618541  3.36273349  3.07638034  8.75945117  0.36154095  2.96234809]
 [ 6.77132866  3.09562298  3.4978527   0.1790556   0.94698953  1.45376415  1.57284445  5.5723547   1.73585855  1.15418911]
 [ 9.02277027  2

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [267]:
Z = np.random.randint(0,10,(10,10))

shape = (5,5)
fill = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)

Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)

Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()

R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

R[r] = Z[z]

print(Z)
print(R)

[[8 6 5 0 4 1 7 3 7 8]
 [2 0 2 7 1 3 0 1 5 0]
 [5 7 8 8 7 2 7 5 9 3]
 [4 9 8 4 7 0 8 7 8 1]
 [6 4 8 1 9 3 6 2 9 8]
 [4 4 7 4 5 3 5 9 0 3]
 [5 8 1 7 2 6 2 1 7 3]
 [5 8 1 8 5 0 1 5 4 8]
 [7 4 6 1 1 2 1 3 2 9]
 [0 4 6 8 8 8 0 2 4 1]]
[[0 0 0 0 0]
 [0 8 6 5 0]
 [0 2 0 2 7]
 [0 5 7 8 8]
 [0 4 9 8 4]]


/Users/mahimairaja/opt/anaconda3/envs/flask/lib/python3.7/site-packages/ipykernel_launcher.py:28: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [270]:
Z = np.arange(1,15,dtype=np.uint32)

R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(Z,'\n\n',R)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

 [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [273]:
Z = np.random.uniform(0,1,(10,10))

U, S, V = np.linalg.svd(Z) 

rank = np.sum(S > 1e-10)
print(Z.shape)
print(rank)

(10, 10)
10


#### 83. How to find the most frequent value in an array?

In [272]:
Z = np.random.randint(0,10,50)

print(np.bincount(Z).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [274]:
Z = np.random.randint(0,5,(10,10))

n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)

C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)

print(C)

[[[[4 0 2]
   [4 2 4]
   [4 0 1]]

  [[0 2 2]
   [2 4 1]
   [0 1 2]]

  [[2 2 2]
   [4 1 3]
   [1 2 1]]

  [[2 2 4]
   [1 3 2]
   [2 1 3]]

  [[2 4 3]
   [3 2 4]
   [1 3 2]]

  [[4 3 3]
   [2 4 0]
   [3 2 4]]

  [[3 3 0]
   [4 0 2]
   [2 4 3]]

  [[3 0 0]
   [0 2 4]
   [4 3 4]]]


 [[[4 2 4]
   [4 0 1]
   [1 2 2]]

  [[2 4 1]
   [0 1 2]
   [2 2 3]]

  [[4 1 3]
   [1 2 1]
   [2 3 2]]

  [[1 3 2]
   [2 1 3]
   [3 2 4]]

  [[3 2 4]
   [1 3 2]
   [2 4 4]]

  [[2 4 0]
   [3 2 4]
   [4 4 0]]

  [[4 0 2]
   [2 4 3]
   [4 0 0]]

  [[0 2 4]
   [4 3 4]
   [0 0 1]]]


 [[[4 0 1]
   [1 2 2]
   [3 0 0]]

  [[0 1 2]
   [2 2 3]
   [0 0 3]]

  [[1 2 1]
   [2 3 2]
   [0 3 4]]

  [[2 1 3]
   [3 2 4]
   [3 4 1]]

  [[1 3 2]
   [2 4 4]
   [4 1 4]]

  [[3 2 4]
   [4 4 0]
   [1 4 0]]

  [[2 4 3]
   [4 0 0]
   [4 0 4]]

  [[4 3 4]
   [0 0 1]
   [0 4 3]]]


 [[[1 2 2]
   [3 0 0]
   [2 3 0]]

  [[2 2 3]
   [0 0 3]
   [3 0 1]]

  [[2 3 2]
   [0 3 4]
   [0 1 2]]

  [[3 2 4]
   [3 4 1]
   [1 2 2]]

  [[2 4 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [277]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
    
    def symetric(Z):
        return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

    S = symetric(np.random.randint(0,10,(5,5)))

    S[2,3] = 42

    print(S)


[[ 3 11  5  9  7]
 [11  3  4  8 12]
 [ 5  4  6 42 11]
 [ 9  8 42  9 16]
 [ 7 12 11 16  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [278]:
p, n = 10, 20

M = np.ones((p,n,n))
V = np.ones((p,n,1))

S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])

print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [280]:
Z = np.ones((16,16))
k = 4

S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
np.arange(0, Z.shape[1], k), axis=1)

print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [281]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] + Z[1:-1,0:-2] + Z[1:-1,2:] + Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)

    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))

for i in range(100): 
    Z = iterate(Z)

print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [283]:
Z = np.arange(10000)

np.random.shuffle(Z)

n = 6

print (Z[np.argpartition(-Z,n)[:n]])

[9995 9999 9996 9994 9998 9997]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [284]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [285]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])

R = np.core.records.fromarrays(Z.T,

names='col1, col2, col3',
formats = 'S8, f8, i8')

print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [292]:
x = np.random.rand(5)

timeit = np.power(x,3)
timeit

array([0.11704891, 0.64664282, 0.11353745, 0.13286148, 0.0597583 ])

In [293]:
timeit = x*x*x
timeit

array([0.11704891, 0.64664282, 0.11353745, 0.13286148, 0.0597583 ])

In [294]:
timeit = np.einsum('i,i,i->i',x,x,x)
timeit

array([0.11704891, 0.64664282, 0.11353745, 0.13286148, 0.0597583 ])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [295]:
A = np.random.randint(0,5,(8,3))

B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)

rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]

print(rows)



[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [296]:
Z = np.random.randint(0,5,(10,3))

E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)

U = Z[~E]

print(Z)

print(U)

[[1 0 4]
 [0 2 2]
 [4 4 4]
 [1 1 0]
 [0 0 1]
 [1 3 4]
 [2 2 2]
 [0 4 3]
 [0 1 2]
 [3 0 2]]
[[1 0 4]
 [0 2 2]
 [1 1 0]
 [0 0 1]
 [1 3 4]
 [0 4 3]
 [0 1 2]
 [3 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [297]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])

B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)

print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [298]:
Z = np.random.randint(0,2,(6,3))

T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))

_, idx = np.unique(T, return_index=True)

uZ = Z[idx]

print(uZ)



[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [299]:
A = np.random.uniform(0,1,10)

B = np.random.uniform(0,1,10)

np.einsum('i->', A) # np.sum(A)

np.einsum('i,i->i', A, B) # A * B

np.einsum('i,i', A, B) # np.inner(A, B)

np.einsum('i,j', A, B) # np.outer(A, B)

array([[0.12198367, 0.3502262 , 0.23893686, 0.2018728 , 0.16976547, 0.39159489, 0.26300228, 0.02972072, 0.34989259, 0.20418047],
       [0.03255817, 0.09347746, 0.06377367, 0.05388106, 0.04531142, 0.10451901, 0.07019688, 0.00793264, 0.09338842, 0.05449699],
       [0.18740621, 0.53806026, 0.36708398, 0.31014165, 0.26081445, 0.60161589, 0.40405623, 0.04566061, 0.53754772, 0.31368697],
       [0.09037537, 0.2594759 , 0.17702375, 0.1495637 , 0.12577599, 0.29012517, 0.19485337, 0.02201952, 0.25922873, 0.15127341],
       [0.19159808, 0.5500955 , 0.37529485, 0.31707885, 0.2666483 , 0.61507273, 0.41309409, 0.04668193, 0.5495715 , 0.32070347],
       [0.12365656, 0.35502921, 0.24221365, 0.20464129, 0.17209364, 0.39696523, 0.26660911, 0.03012831, 0.35469103, 0.2069806 ],
       [0.06822314, 0.19587483, 0.13363283, 0.11290361, 0.09494659, 0.21901155, 0.14709216, 0.01662223, 0.19568825, 0.11419424],
       [0.24002691, 0.68913908, 0.47015536, 0.39722453, 0.33404702, 0.77054013, 0.51750883, 0.058

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [301]:
phi = np.arange(0, 10*np.pi, 0.1)

a = 1

x = a*phi*np.cos(phi)

y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths

r = np.zeros_like(x)

r[1:] = np.cumsum(dr) # integrate path

r_int = np.linspace(0, r.max(), 200) # regular spaced path

x_int = np.interp(r_int, r, x) # integrate path

y_int = np.interp(r_int, r, y)

print(x,'\n',y)

[  0.           0.09950042   0.19601332   0.28660095   0.3684244    0.43879128   0.49520137   0.53538953   0.55736537   0.55944897   0.54030231   0.49895573   0.43482931   0.34774848   0.237954     0.1061058   -0.04671924  -0.21903564  -0.40896377  -0.61425018  -0.83229367  -1.06017682  -1.29470246  -1.53243485  -1.76974492  -2.00285904  -2.22791076  -2.44099478  -2.63822255  -2.81577868  -2.96997749  -3.09731897  -3.19454328  -3.25868324  -3.28711385  -3.27759841  -3.2283303   -3.13797012  -3.00567731  -2.83113599  -2.61457448  -2.35677818  -2.05909545  -1.72343644  -1.35226463  -0.9485811   -0.51590162  -0.05822672   0.41999512   0.91391061   1.41831093   1.92768649   2.43628669   2.93818398   3.42734153   3.89768376   4.34316892   4.75786287   5.1360132    5.47212274   5.76102172   5.99793747   6.178561     6.29910941   6.35638348   6.34781957   6.27153511   6.12636709   5.91190293   5.62850319   5.27731578   4.86028133   4.38012946   3.84036588   3.24525022   2.59976488   1.9095748

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [302]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],

[2.0, 0.0, 1.0, 1.0],

[1.5, 2.5, 1.0, 0.0]])

n = 4

M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)

M &= (X.sum(axis=-1) == n)

print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [303]:
X = np.random.randn(100) # random 1D array

N = 1000 # number of bootstrap samples

idx = np.random.randint(0, X.size, (N, X.size))

means = X[idx].mean(axis=1)

confint = np.percentile(means, [2.5, 97.5])

print(confint)

[-0.08499665  0.30899674]
